### ISSUE TITLE
COVID SEIR fit

### ISSUE THREAD

**Issue by pinkfloydisch** [bnsreenu/python_for_microscopists#2]
Hi, First thanks a lot for your very useful and productive videos and codes.
May I ask you please teach me how to predict the COVID with SEIR model and fit the data with SEIR model ...  I saw your codes and video with exponential growth, not SEIR

Thanks

**Comment by bnsreenu** [comment]
SEIR falls into disease modeling and really does not fit into the topic of machine learning, especially for image processing. Moreover, it is not my expertise anyway.
