### ISSUE TITLE
Docker in ubuntu is not working as smooth

### ISSUE THREAD

**Issue by nlrahimi** [bnsreenu/python_for_microscopists#5]
Hello Sreeni,

Thank you for the awesome tutorial videos.
I followed the youtube tutorial to make a container on my ubuntu-os system and faced a few issues did not happen in tutorial. Though I exerted the suggestions in web the problem was not solved and would appreciate it if you can guide me here.
in the beginning the terminal generated this error:
 `_no such option: --no-cashe-dir
The command '/bin/sh -c pip install --no-cashe-dir -r requirements.txt' returned a non-zero code: 2_
`
 when running the last command in Dockerfile:
`RUN pip install --no-cashe-dir -r requirements.txt`

and when running `sudo docker run -v` for mapping, I faced a long-standing issue: `_docker: invalid reference format_`

I could not solve this problem looking to web and thought maybe you might figure what went wrong.

Respectfully 
Nilla

**Comment by bnsreenu** [comment]
My video was on Docker for Windows. I am not familiar with Linux when it comes to running Docker. In fact, I would have thought it would be more straightforward to use Docker on Linux compared to Windows. I hope you solved the issue by now.
