### ISSUE TITLE
[Autoencoder] Scaling L Channel for Image Colorization

### ISSUE THREAD

**Issue by prmondal** [bnsreenu/python_for_microscopists#6]
Don't we need to divide L channel by 100 since original values vary between 0 to 100?
https://github.com/bnsreenu/python_for_microscopists/blob/master/090a-autoencoder_colorize_V0.2.py#L47

Same needs to be applied during prediction here https://github.com/bnsreenu/python_for_microscopists/blob/master/090a-autoencoder_colorize_V0.2.py#L112.

Anyway nice tutorial. Thanks.

**Comment by prmondal** [comment]
@bnsreenu

**Comment by bnsreenu** [comment]
Yes, dividing L channel by 100 can help speedup the training process. Since the only input to the network is L, it does not matter much if you scale or do not scale. I do recommend scaling as it is a good practice. Thanks for catching my bad habit :)
