### ISSUE TITLE
Licening / copyright

### ISSUE THREAD

**Issue by haesleinhuepf** [bnsreenu/python_for_microscopists#75]
Hi Sreeni @bnsreenu ,

you're maintaining a fantastic resource here in this repository! I was just wondering under which conditions one could reuse the code published here. Would you mind adding a LICENSE file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by bnsreenu** [comment]
I initially created this repository without expecting its widespread adoption and didn't mind if others used my code without attribution. However, given its popularity, it's now important to include a license file to formally convey my intentions. I will proceed with adding a license file. Thank you to Robert and Majed for their valuable input.

**Comment by haesleinhuepf** [comment]
An MIT license was obviously added. Big thanks Sreeni!
