### ISSUE TITLE
Sandstone images used in learning courses

### ISSUE THREAD

**Issue by mahyad55** [bnsreenu/python_for_microscopists#8]
Hello Sreeni,

Thanks for your excellent learning courses, they are really amazing! Could you please explain a little about the attached images which are taken from your GitHub page? Is there any document that I can read about these images?

Thanks for your favor
![Sandstone_Versa0000](https://user-images.githubusercontent.com/39349800/102058361-9b3a1b80-3e04-11eb-93a6-0e900b06a5ee.jpg)

**Comment by bnsreenu** [comment]
I finally found a way to share the sandstone dataset that gets used quite often in many of my examples. Here is the link: https://drive.google.com/file/d/1HWtBaSa-LTyAMgf2uaz1T9o1sTWDBajU/view?usp=sharing
Please go through the Readme document for more information.
